import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between items-center py-4 px-4">
          <h1 className="text-xl font-bold">Simon Stancovich</h1>
          <nav>
            <Link href="/" className="px-3 py-2 hover:underline">
              Homer
            </Link>
            <Link href="/projects" className="px-3 py-2 hover:underline">
              Projects
            </Link>
            <Link href="/about" className="px-3 py-2 hover:underline">
              About
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
